### ISSUE TITLE
kcrapclient and ./test-ntlm* fail with 'Invalid realm for service principal'

### ISSUE THREAD

**Issue by thebigb** [fuhry/kcrap#2]
Hi Dan,

I've been trying to get kcrapclient to authenticate for FreeRADIUS, but libkcrap keeps returning _Invalid realm for service principal_ for both the kcrapclient and the test binaries.

I'm new to Kerberos, so it is entirely possible that I've missed an essential setting somewhere. However a basic test with `kinit user` and the password `SecREt01` seem to work fine. 

I'm running MIT Kerberos 1.13.2. Could this be an incompatibility?

Thanks!

**Comment by FransUrbo** [comment]
This repo looks like an old version. There's a newer one (I think) at https://github.com/grawity/kcrap-lnf. However, I get the same there..

**Comment by fuhry** [comment]
Closing this issue due to 5+ years of inactivity. If this is still a problem please reopen.
